# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c4f69271677bc0751f60b1abd71c5e60b9c671ef07529aedc1085c9414da108fb56a55b667d797358ee30b460afed9f58080be6791947ddfcaecceeac4382f

test:
  secret_key_base: 1656d6d06279f2b18a6d55565d970e1bdbc11b80b5bef58027008b46a78bc650616f0585c0a866f8dcf24ca8041fa658926106604fdd69de82b5c04130298268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
